### ISSUE TITLE
Upstream support for Docker deployment

### ISSUE THREAD

**Issue by TheAssassin** [DanielnetoDotCom/YouPHPTube#362]
This software seems to work very well, and I like the architecture of having an encoder and a main page.

However, the deployment is unnecessarily hard, as there's quite a list of dependencies involved, etc. So I developed my own Docker deployment based on https://github.com/hannah98/youphptube-docker (which is a little outdated).

I'm probably going to publish this anyway, but I'd like to know whether you'd be interested to ship an official Docker configuration, and maybe publish your own Docker images on Dockerhub, quay.io, etc. It should help users to get started more easily, quickly set up demo environments, etc.

**Comment by DanielnetoDotCom** [comment]
@TheAssassin Great, please share it with us

**Comment by TheAssassin** [comment]
I need to upgrade my infrastructure later. I'll send a PR when I'm ready.

**Comment by TheAssassin** [comment]
I added two PRs with Docker configs that work. They're not perfect yet, it'd be better not to install apache2 and configure it as-is, and rather use the official PHP container.

The following docker-compose file can be used to deploy both containers after cloning both repositories to a directory where the file needs to be put into:

```
version: "2"

services:
  mariadb:
    image: mariadb:10
    env_file: env
    restart: unless-stopped

  youphptube:
    build: youphptube
    ports:
     - 127.0.0.1:15000:80
    volumes:
     - videos_vol:/var/www/html/videos
    links:
      - mariadb:mariadb
      - youphptube-encoder:youphptube-encoder
    restart: unless-stopped

  youphptube-encoder:
    build: youphptube-encoder
    ports:
      - 127.0.0.1:15001:80
    links:
      - mariadb:mariadb    
    volumes:
      - videos_encoder_vol:/var/www/html/videos
    restart: unless-stopped

volumes:
  videos_vol:
  videos_encoder_vol:
```

Users of this file are also expected to create a file called `env` next to the `docker-compose.yml` file, containing a line:
```
MYSQL_ROOT_PASSWORD=<your pass, can be auto generated>
```

This password can then be used with the root user in the installation assistant.

You can choose to use specific Git tags by checking them out before running `docker-compose up -d --build`. In the future, you may choose to publish Docker images on Docker Hub or some other public registry like https://quay.io.

Tested with YouPHPTube 4.2+.

All the files provided here are explicitly licensed under the terms of the CC-0 license.
